### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by ghost** [FA15bZombieSurvival/FreshFlesh#2]
```> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (/home/jonathan/Schule/Mittelstufenprojekt/FreshFlesh/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/jonathan/Schule/Mittelstufenprojekt/FreshFlesh/server.js:36:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! freshflesh@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freshflesh@0.0.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freshflesh package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freshflesh
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freshflesh
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jonathan/Schule/Mittelstufenprojekt/FreshFlesh/npm-debug.log```

**Comment by StamplerJ** [comment]
Sieht danach aus, dass Port 80 gesperrt ist. Vielleicht durch Skype?
Da es allgemein eine schlechte Idee ist den Server lokal auf Port 80 laufen zu lassen, habe ich ihn jetzt in 3000 geändert.

**Comment by ghost** [comment]
Top :D Hatte keine Lust drüber nachzudenken. Habe gestern nur kurz versucht ihn zu starten :p
